# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transaction.ui',
# licensing of 'transaction.ui' applies.
#
# Created: Sun Jun 16 21:23:02 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(391, 232)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(-1, 4, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.valueEdit = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.valueEdit.sizePolicy().hasHeightForWidth())
        self.valueEdit.setSizePolicy(sizePolicy)
        self.valueEdit.setObjectName("valueEdit")
        self.gridLayout.addWidget(self.valueEdit, 5, 0, 2, 2)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setStyleSheet("font: 63 11pt \"Segoe UI Semibold\";")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 2, 1, 2)
        self.categoryCombo = QtWidgets.QComboBox(Dialog)
        self.categoryCombo.setObjectName("categoryCombo")
        self.gridLayout.addWidget(self.categoryCombo, 3, 0, 1, 2)
        self.dateEdit = QtWidgets.QDateEdit(Dialog)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 3, 2, 1, 2)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setStyleSheet("font: 63 11pt \"Segoe UI Semibold\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 2)
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 5, 2, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 5, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 8, 3, 1, 1)
        self.accCombo = QtWidgets.QComboBox(Dialog)
        self.accCombo.setObjectName("accCombo")
        self.gridLayout.addWidget(self.accCombo, 6, 2, 1, 2)
        self.commentEdit = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commentEdit.sizePolicy().hasHeightForWidth())
        self.commentEdit.setSizePolicy(sizePolicy)
        self.commentEdit.setObjectName("commentEdit")
        self.gridLayout.addWidget(self.commentEdit, 8, 0, 1, 3)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setStyleSheet("font: 63 11pt \"Segoe UI Semibold\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setStyleSheet("font: 63 11pt \"Segoe UI Semibold\";")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setStyleSheet("font: 63 11pt \"Segoe UI Semibold\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 2, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(9, 0, 0, 4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Revenue = QtWidgets.QRadioButton(self.groupBox)
        self.Revenue.setChecked(True)
        self.Revenue.setObjectName("Revenue")
        self.horizontalLayout.addWidget(self.Revenue)
        self.Expense = QtWidgets.QRadioButton(self.groupBox)
        self.Expense.setChecked(False)
        self.Expense.setObjectName("Expense")
        self.horizontalLayout.addWidget(self.Expense)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Dialog", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "Fonte/Destino", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "Valor (R$)", None, -1))
        self.radioButton.setText(QtWidgets.QApplication.translate("Dialog", "Conta", None, -1))
        self.radioButton_2.setText(QtWidgets.QApplication.translate("Dialog", "Cartão", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("Dialog", "OK", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "Categoria", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "Comentário", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "Data", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("Dialog", "Tipo de Transação", None, -1))
        self.Revenue.setText(QtWidgets.QApplication.translate("Dialog", "Receita", None, -1))
        self.Expense.setText(QtWidgets.QApplication.translate("Dialog", "Despesa", None, -1))

