# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'categoryconfiguration.ui',
# licensing of 'categoryconfiguration.ui' applies.
#
# Created: Fri Jul  5 21:45:38 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(319, 256)
        self.gridLayout_5 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.Add = QtWidgets.QWidget()
        self.Add.setObjectName("Add")
        self.gridLayout = QtWidgets.QGridLayout(self.Add)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.Add)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.Add)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.Add)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.frame = QtWidgets.QFrame(self.Add)
        self.frame.setMinimumSize(QtCore.QSize(200, 100))
        self.frame.setMaximumSize(QtCore.QSize(2000, 1000))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.gridLayout.addWidget(self.frame, 6, 0, 1, 3)
        self.label_21 = QtWidgets.QLabel(self.Add)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 4, 1, 1, 1)
        self.tabWidget.addTab(self.Add, "")
        self.Edit = QtWidgets.QWidget()
        self.Edit.setObjectName("Edit")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Edit)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_10 = QtWidgets.QLabel(self.Edit)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 2, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.Edit)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_4.addWidget(self.comboBox, 1, 0, 1, 3)
        self.label_11 = QtWidgets.QLabel(self.Edit)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 0, 1, 3)
        self.frame_2 = QtWidgets.QFrame(self.Edit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(200, 100))
        self.frame_2.setMaximumSize(QtCore.QSize(2000, 1000))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 2, 0, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 1, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 0, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 1, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 0, 0, 1, 2)
        self.horizontalLayout_2.addLayout(self.gridLayout_3)
        self.gridLayout_4.addWidget(self.frame_2, 4, 0, 1, 3)
        self.label_20 = QtWidgets.QLabel(self.Edit)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 2, 1, 1, 1)
        self.tabWidget.addTab(self.Edit, "")
        self.Rename = QtWidgets.QWidget()
        self.Rename.setObjectName("Rename")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Rename)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_9 = QtWidgets.QLabel(self.Rename)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.comboBox_2 = QtWidgets.QComboBox(self.Rename)
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout.addWidget(self.comboBox_2)
        self.label_12 = QtWidgets.QLabel(self.Rename)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Rename)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget.addTab(self.Rename, "")
        self.Remove = QtWidgets.QWidget()
        self.Remove.setObjectName("Remove")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Remove)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_13 = QtWidgets.QLabel(self.Remove)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.comboBox_3 = QtWidgets.QComboBox(self.Remove)
        self.comboBox_3.setObjectName("comboBox_3")
        self.verticalLayout_2.addWidget(self.comboBox_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.tabWidget.addTab(self.Remove, "")
        self.gridLayout_5.addWidget(self.tabWidget, 0, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_5.addWidget(self.pushButton, 1, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_5.addWidget(self.pushButton_2, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Dialog", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "Cor", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "Categoria", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "Comentário", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "R$", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Dialog", "Banco", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Dialog", "10/10/2010", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "00.0", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog", "Category", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("Dialog", "COR", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Add), QtWidgets.QApplication.translate("Dialog", "Adicionar", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Dialog", "Cor", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Dialog", "Categoria", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("Dialog", "Comentário", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("Dialog", "R$", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("Dialog", "Banco", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("Dialog", "10/10/2010", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("Dialog", "00.0", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("Dialog", "Category", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("Dialog", "OLD", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Edit), QtWidgets.QApplication.translate("Dialog", "Editar Cor", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Dialog", "Categoria", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("Dialog", "Novo Nome", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Rename), QtWidgets.QApplication.translate("Dialog", "Renomear", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("Dialog", "Categoria", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Remove), QtWidgets.QApplication.translate("Dialog", "Remover", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("Dialog", "Sair", None, -1))
        self.pushButton_2.setText(QtWidgets.QApplication.translate("Dialog", "Aplicar", None, -1))

