# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui',
# licensing of 'mainwindow.ui' applies.
#
# Created: Sat Jun 15 18:03:24 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.page_2)
        self.graphicsView_2.setMinimumSize(QtCore.QSize(0, 200))
        self.graphicsView_2.setMaximumSize(QtCore.QSize(16777215, 300))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.gridLayout_6.addWidget(self.graphicsView_2, 0, 0, 1, 2)
        self.scrollArea = QtWidgets.QScrollArea(self.page_2)
        self.scrollArea.setMinimumSize(QtCore.QSize(700, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(700, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 698, 285))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.frame_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_9.setMinimumSize(QtCore.QSize(150, 100))
        self.frame_9.setMaximumSize(QtCore.QSize(150, 100))
        self.frame_9.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_6 = QtWidgets.QLabel(self.frame_9)
        self.label_6.setObjectName("label_6")
        self.gridLayout_9.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_9)
        self.label_19.setObjectName("label_19")
        self.gridLayout_9.addWidget(self.label_19, 0, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_9)
        self.label_20.setObjectName("label_20")
        self.gridLayout_9.addWidget(self.label_20, 1, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_9)
        self.label_21.setObjectName("label_21")
        self.gridLayout_9.addWidget(self.label_21, 1, 1, 1, 2)
        self.label_22 = QtWidgets.QLabel(self.frame_9)
        self.label_22.setObjectName("label_22")
        self.gridLayout_9.addWidget(self.label_22, 2, 0, 1, 3)
        self.gridLayout_12.addWidget(self.frame_9, 0, 3, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_4.setMinimumSize(QtCore.QSize(150, 100))
        self.frame_4.setMaximumSize(QtCore.QSize(150, 100))
        self.frame_4.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setObjectName("label_5")
        self.gridLayout_8.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_8.addWidget(self.label_4, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 1, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 2, 0, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_8.addWidget(self.pushButton_2, 2, 2, 1, 1)
        self.gridLayout_12.addWidget(self.frame_4, 0, 0, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_10.setMinimumSize(QtCore.QSize(150, 100))
        self.frame_10.setMaximumSize(QtCore.QSize(150, 100))
        self.frame_10.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_23 = QtWidgets.QLabel(self.frame_10)
        self.label_23.setObjectName("label_23")
        self.gridLayout_10.addWidget(self.label_23, 0, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.frame_10)
        self.label_24.setObjectName("label_24")
        self.gridLayout_10.addWidget(self.label_24, 0, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.frame_10)
        self.label_25.setObjectName("label_25")
        self.gridLayout_10.addWidget(self.label_25, 1, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.frame_10)
        self.label_26.setObjectName("label_26")
        self.gridLayout_10.addWidget(self.label_26, 1, 1, 1, 2)
        self.label_27 = QtWidgets.QLabel(self.frame_10)
        self.label_27.setObjectName("label_27")
        self.gridLayout_10.addWidget(self.label_27, 2, 0, 1, 3)
        self.gridLayout_12.addWidget(self.frame_10, 0, 2, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_5.setMinimumSize(QtCore.QSize(150, 100))
        self.frame_5.setMaximumSize(QtCore.QSize(150, 100))
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_28 = QtWidgets.QLabel(self.frame_5)
        self.label_28.setObjectName("label_28")
        self.gridLayout_11.addWidget(self.label_28, 0, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.frame_5)
        self.label_29.setObjectName("label_29")
        self.gridLayout_11.addWidget(self.label_29, 0, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.frame_5)
        self.label_30.setObjectName("label_30")
        self.gridLayout_11.addWidget(self.label_30, 1, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.frame_5)
        self.label_31.setObjectName("label_31")
        self.gridLayout_11.addWidget(self.label_31, 1, 1, 1, 2)
        self.label_32 = QtWidgets.QLabel(self.frame_5)
        self.label_32.setObjectName("label_32")
        self.gridLayout_11.addWidget(self.label_32, 2, 0, 1, 3)
        self.gridLayout_12.addWidget(self.frame_5, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem, 2, 0, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_11.setMinimumSize(QtCore.QSize(150, 100))
        self.frame_11.setMaximumSize(QtCore.QSize(150, 100))
        self.frame_11.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_36 = QtWidgets.QLabel(self.frame_11)
        self.label_36.setObjectName("label_36")
        self.gridLayout_13.addWidget(self.label_36, 0, 2, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.frame_11)
        self.label_37.setObjectName("label_37")
        self.gridLayout_13.addWidget(self.label_37, 0, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.frame_11)
        self.label_38.setObjectName("label_38")
        self.gridLayout_13.addWidget(self.label_38, 1, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.frame_11)
        self.label_39.setObjectName("label_39")
        self.gridLayout_13.addWidget(self.label_39, 1, 1, 1, 2)
        self.label_40 = QtWidgets.QLabel(self.frame_11)
        self.label_40.setObjectName("label_40")
        self.gridLayout_13.addWidget(self.label_40, 2, 0, 1, 3)
        self.gridLayout_12.addWidget(self.frame_11, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_6.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.page_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_7.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_7.addWidget(self.pushButton_4, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_3.setGeometry(QtCore.QRect(70, 20, 69, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_34 = QtWidgets.QLabel(self.groupBox)
        self.label_34.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.label_34.setObjectName("label_34")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_4.setGeometry(QtCore.QRect(70, 50, 69, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.label_33 = QtWidgets.QLabel(self.groupBox)
        self.label_33.setGeometry(QtCore.QRect(10, 30, 47, 13))
        self.label_33.setObjectName("label_33")
        self.label_35 = QtWidgets.QLabel(self.groupBox)
        self.label_35.setGeometry(QtCore.QRect(180, 20, 47, 13))
        self.label_35.setObjectName("label_35")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_5.setGeometry(QtCore.QRect(280, 20, 69, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.gridLayout_7.addWidget(self.groupBox, 0, 0, 1, 2)
        self.gridLayout_6.addWidget(self.frame, 1, 1, 1, 1)
        self.stackFrame.addWidget(self.page_2)

        self.retranslateUi(MainWindow)
        self.stackFrame.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.showHideSide.setText(QtWidgets.QApplication.translate("MainWindow", "<<", None, -1))
        self.payGroupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Pagamentos", None, -1))
        self.CCGroupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Cartão de Crédito", None, -1))
        self.Label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Cartão de Crédito", None, -1))
        self.currencyLabel_2.setText(QtWidgets.QApplication.translate("MainWindow", "R$", None, -1))
        self.valueLabel_2.setText(QtWidgets.QApplication.translate("MainWindow", "00,00", None, -1))
        self.accGroupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Conta", None, -1))
        self.Label.setText(QtWidgets.QApplication.translate("MainWindow", "Conta", None, -1))
        self.currencyLabel.setText(QtWidgets.QApplication.translate("MainWindow", "R$", None, -1))
        self.valueLabel.setText(QtWidgets.QApplication.translate("MainWindow", "00,00", None, -1))
        self.budgetGroupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Orçamento", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Date", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("MainWindow", "Category", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("MainWindow", "R$", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("MainWindow", "00,00", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("MainWindow", "Comment", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Date", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Category", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "R$", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "00,00", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Comment", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("MainWindow", "Date", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("MainWindow", "Category", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("MainWindow", "R$", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("MainWindow", "00,00", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("MainWindow", "Comment", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("MainWindow", "Date", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("MainWindow", "Category", None, -1))
        self.label_30.setText(QtWidgets.QApplication.translate("MainWindow", "R$", None, -1))
        self.label_31.setText(QtWidgets.QApplication.translate("MainWindow", "00,00", None, -1))
        self.label_32.setText(QtWidgets.QApplication.translate("MainWindow", "Comment", None, -1))
        self.label_36.setText(QtWidgets.QApplication.translate("MainWindow", "Date", None, -1))
        self.label_37.setText(QtWidgets.QApplication.translate("MainWindow", "Category", None, -1))
        self.label_38.setText(QtWidgets.QApplication.translate("MainWindow", "R$", None, -1))
        self.label_39.setText(QtWidgets.QApplication.translate("MainWindow", "00,00", None, -1))
        self.label_40.setText(QtWidgets.QApplication.translate("MainWindow", "Comment", None, -1))
        self.pushButton_3.setText(QtWidgets.QApplication.translate("MainWindow", "PushButton", None, -1))
        self.pushButton_4.setText(QtWidgets.QApplication.translate("MainWindow", "PushButton", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Filtros", None, -1))
        self.label_34.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.label_33.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.label_35.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.AccPageButton.setText(QtWidgets.QApplication.translate("MainWindow", "Contas", None, -1))
        self.CCPageButton.setText(QtWidgets.QApplication.translate("MainWindow", "Cartões de Crédito", None, -1))
        self.BudgetPageButton.setText(QtWidgets.QApplication.translate("MainWindow", "Orçamento", None, -1))
        self.TablesPageButton.setText(QtWidgets.QApplication.translate("MainWindow", "Tabelas", None, -1))
        self.InvestPageButton.setText(QtWidgets.QApplication.translate("MainWindow", "Investimentos Geral", None, -1))
        self.BondsPageButton.setText(QtWidgets.QApplication.translate("MainWindow", "Renda Fixa", None, -1))
        self.StocksPageButton.setText(QtWidgets.QApplication.translate("MainWindow", "Ações", None, -1))
        self.toolBar.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "toolBar", None, -1))
        self.Home.setText(QtWidgets.QApplication.translate("MainWindow", "Home", None, -1))
        self.Home.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Ir para página inicial", None, -1))
        self.RevenueAcc.setText(QtWidgets.QApplication.translate("MainWindow", "RevenueAcc", None, -1))
        self.RevenueAcc.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Receita", None, -1))
        self.ExpenseAcc.setText(QtWidgets.QApplication.translate("MainWindow", "Expense", None, -1))
        self.ExpenseAcc.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Adicionar despesa", None, -1))
        self.AddAcc.setText(QtWidgets.QApplication.translate("MainWindow", "AddAcc", None, -1))
        self.AddAcc.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Adicionar conta", None, -1))
        self.RmvAcc.setText(QtWidgets.QApplication.translate("MainWindow", "RmvAcc", None, -1))
        self.RmvAcc.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Remover conta", None, -1))
        self.AddCC.setText(QtWidgets.QApplication.translate("MainWindow", "AddCC", None, -1))
        self.AddCC.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Adicionar cartão de crédito", None, -1))
        self.RmvCC.setText(QtWidgets.QApplication.translate("MainWindow", "RmvCC", None, -1))
        self.RmvCC.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Remover cartão de crédito", None, -1))
        self.ExpenseCC.setText(QtWidgets.QApplication.translate("MainWindow", "ExpenseCC", None, -1))
        self.ExpenseCC.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Despesa cartão de crédito", None, -1))
        self.Transfer.setText(QtWidgets.QApplication.translate("MainWindow", "Transfer", None, -1))
        self.Transfer.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Transferência entre contas", None, -1))
        self.Categories.setText(QtWidgets.QApplication.translate("MainWindow", "EditCategories", None, -1))
        self.Categories.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Editar categorias", None, -1))
